Repository Abipravi1/Hacktoberfest2022-python, pull requests merged in 2022-10, with the labels that each got.

#49 Updated
  twitter url extracter.py
Labels: hacktoberfest-accepted, accepted

#51 Update README.md
  README.md
Labels: hacktoberfest-accepted, accepted

#50 matrix inverse added and matrix rotate added
  matrix_inverse.py
  rotate_matrix.py
Labels: hacktoberfest, accepted

#53 added quicksort program for python
  QuickSort/quicksort.py
Labels: hacktoberfest-accepted, accepted

#52 Added script for getting length of longest com substring
  longest_common_substring.py
Labels: question

#56 created fibonacci series in three lines
  fibo.py
Labels: hacktoberfest-accepted, accepted

#57 count set bits in positive integer
  count_set_bits_positive_integer.py
Labels: hacktoberfest, accepted

#58 hangman game using python
  hangman.py
Labels: question

#61 Python program to check a password's strength
  Password_Strength_Checker.py
Labels: hacktoberfest-accepted, accepted

#63 add simple student registration program
  student-registration-program.py
Labels: hacktoberfest-accepted, accepted

#80 add/subtract matrices
  add_subtract_matrices.py
Labels: hacktoberfest-accepted, accepted

#78 adding an int array rotator in python
  int_array_rotator.py
Labels: hacktoberfest-accepted, accepted

#75 get ip/hostname with socket library
  socket_ip_hostname.py
Labels: hacktoberfest-accepted, accepted

#73 Python Program to find the value of a sequence
  odd_no_square.py
Labels: hacktoberfest-accepted, accepted

#72 Added Working Red-Black tree code file
  Red-Black Tree.py
Labels: hacktoberfest-accepted, accepted

#68 Add queue structure
  data_structures/queue/__init__.py
  data_structures/queue/circular_queue.py
  data_structures/queue/circular_queue_linked_list.py
  data_structures/queue/double_ended_queue.py
  data_structures/queue/linked_queue.py
  data_structures/queue/priority_queue_using_list.py
  data_structures/queue/queue_on_list.py
  data_structures/queue/queue_on_pseudo_stack.py
Labels: hacktoberfest-accepted, accepted

#69 Add stack structure
  data_structures/stacks/__init__.py
  data_structures/stacks/balanced_parentheses.py
  data_structures/stacks/dijkstras_two_stack_algorithm.py
  data_structures/stacks/evaluate_postfix_notations.py
  data_structures/stacks/infix_to_postfix_conversion.py
  data_structures/stacks/infix_to_prefix_conversion.py
  data_structures/stacks/next_greater_element.py
  data_structures/stacks/postfix_evaluation.py
  data_structures/stacks/prefix_evaluation.py
  data_structures/stacks/stack.py
  data_structures/stacks/stack_with_doubly_linked_list.py
  data_structures/stacks/stack_with_singly_linked_list.py
  data_structures/stacks/stock_span_problem.py
Labels: hacktoberfest-accepted, accepted

#85 added file maximum_sum_subarray.py
  maximum_sum_subarray.py
Labels: hacktoberfest-accepted, accepted

#71 Create insertion sort
  insertion_sort.py
Labels: hacktoberfest-accepted, accepted

#92 Added MergeSort algorithm..!
  MergeSort.py
Labels: hacktoberfest-accepted, accepted

#93 Create Stone_Paper_Scissor_Game.py
  Stone Paper Scissor/Stone_Paper_Scissor_Game.py
Labels: hacktoberfest-accepted, accepted

#96 Create Guess_The_Number.py
  Guess the Number/Guess_The_Number.py
Labels: hacktoberfest-accepted, accepted

#100 Python Program to check for palindromic numbers
  palindromicnumber.py
Labels: hacktoberfest-accepted, accepted

#99 Web Crawler
  Python-Web-Crawler/README.md
  Python-Web-Crawler/demo.py
  Python-Web-Crawler/domain.py
  Python-Web-Crawler/link_finder.py
  Python-Web-Crawler/main.py
  Python-Web-Crawler/spider.py
Labels: hacktoberfest-accepted, accepted

#104 Pull request
  to-do-list.py
Labels: hacktoberfest-accepted, accepted

#106 reverse of a number
  WhatsApp Image 2022-10-02 at 6.04.45 PM.jpeg
Labels: hacktoberfest-accepted, accepted

#103 Scraping timesjobs.com
  scrapping_timesjobs_website.py
Labels: hacktoberfest-accepted, accepted

#102 Contribution of Edmond22-prog: Hashing script
  hashing.py
Labels: hacktoberfest-accepted, accepted

#101 Added factorial.py file
  factorial.py
Labels: hacktoberfest-accepted, accepted

#98 Create Hand_Cricket_Game.py
  Hand Cricket/Hand_Cricket_Game.py
Labels: hacktoberfest-accepted, accepted

#97 Create PigLatin in Python
  PigLatin in Python
Labels: accepted

#94 Added DiagonalDifference calculation code...!
  diagonaldifference.py
Labels: hacktoberfest-accepted, accepted

#91 Add Whatsapp-scheduler
  whatsapp-scheduler.py
Labels: hacktoberfest-accepted, accepted

#70 Create menace.py
  menace.py
Labels: hacktoberfest-accepted, accepted

#74 I add Some fun project using Python
  Heart_in_python_using_turtle.py
  Snake_game_using_pygame.py
  national_flag_turtle.py
  print_the-elements_of_an_array_in_reverse_order.py
Labels: hacktoberfest-accepted, accepted

#108 created morse_code.py
  morse_code.py
Labels: hacktoberfest-accepted, accepted

#109 Checkpass.py
  checkpass.py
Labels: hacktoberfest-accepted, accepted

#110 Linked List problem
  data_structures/linked_list/linkedlist.py
Labels: hacktoberfest-accepted, accepted

#111 Create snakeWaterGun.py
  snakeWaterGun.py
Labels: hacktoberfest-accepted, accepted

#115 issue number #107 Median in a data stream
  Median_in_a_data_stream.py
Labels: hacktoberfest-accepted, accepted

#114 Create blink.py
  blink-detector/blink.py
Labels: hacktoberfest-accepted, accepted

#119 Create Aerial-distance-calculator.py
  Aerial-distance-calculator.py
Labels: hacktoberfest-accepted, accepted

#116 Create Radix-Sort.py
  Radix-Sort.py
Labels: hacktoberfest-accepted, accepted

#122 Create FIzzBuzz.py
  FizzBuzz.py
Labels: hacktoberfest-accepted, accepted

#113 Create Double_linked_list.py
  Double_linked_list.py
Labels: hacktoberfest-accepted, accepted

#121 Create LR.py
  Advanced python programs/LR.py
Labels: hacktoberfest-accepted, accepted

#123 Added program to swap columns in zig-zag manner
  Arrays and Matrix/column_zig_zag_swap.py
Labels: hacktoberfest-accepted, accepted

#112 Created progress_bar.py
  progress_bar.py
Labels: hacktoberfest-accepted, accepted

#129 Create ArmstrongNumber.py
  Python Basic Programs/ArmstrongNumber.py
Labels: hacktoberfest-accepted, accepted

#126 GUI For Database using Python
  PYTHON GUI/GUI_For_Database.py
Labels: hacktoberfest-accepted, accepted

#134 Added avengers name guess game
  Python Basic Programs/avengers.py
Labels: hacktoberfest-accepted, accepted

#133 Quadratic Equation Solver in Python
  Python Basic Programs/Quadratic Equation Solver.py
Labels: hacktoberfest-accepted, accepted

#136 Added Introsort.py
  Arrays and Matrix/Introsort.py
Labels: hacktoberfest-accepted, accepted

#139 Print diamond pattern
  Python Basic Programs/diamond pattern.py
Labels: hacktoberfest-accepted, accepted

#138 Password Checker in C
  Python Basic Programs/Password Checker.py
Labels: hacktoberfest-accepted, accepted

#137 Added Palindrome_string.py
  Python Basic Programs/palindrome_string.py
Labels: hacktoberfest-accepted, accepted

#144 Added A News scrapper
  Web and  Automation and Networking/Scrapper.py
Labels: hacktoberfest-accepted, accepted

#140 Tic Tac Toe in Python
  Tic Tac Toe.py
Labels: hacktoberfest-accepted, accepted

#142 LEETCODE solution- Set Matrix Zeroes
  Arrays and Matrix/Leetcode-question-Set-Matrix-Zeroes.py
Labels: hacktoberfest-accepted, accepted

#143 Added-Leetcode-ques-Sum-of-Even-Numbers-After-Queries
  Arrays and Matrix/Leetcode-question-Sum-of-Even-Numbers-After-Queries.py
Labels: hacktoberfest-accepted, accepted

#145 Create keylogger.py
  Python Basic Programs/keylogger.py
Labels: hacktoberfest-accepted, accepted

#146 Digital_clock
  Digital_clock.py
Labels: hacktoberfest-accepted, accepted

#151 Added Array Operations
  py.py
Labels: hacktoberfest-accepted, accepted

#152 CEO FINDER
  Web and  Automation and Networking/Financial Service main.xlsx
  Web and  Automation and Networking/data.xlsx
  Web and  Automation and Networking/file.xlsx
  Web and  Automation and Networking/main.py
Labels: hacktoberfest-accepted, accepted

#171 eye blink program through python
  AI ML/blink-detector/eye_blink.py
Labels: hacktoberfest-accepted, accepted

#170 shell sort using python
  Arrays and Matrix/shell_sort.py
Labels: hacktoberfest-accepted, accepted

#169 Rotate Matrix in Python
  Arrays and Matrix/matrix_rotation.py
Labels: hacktoberfest-accepted, accepted

#166 Added Tkinter Calculator
  PYTHON GUI/calculator.py
Labels: hacktoberfest-accepted, accepted

#155 Tossing a coin
  toss.py
Labels: hacktoberfest-accepted, accepted

#168 Create diamond_asterisk.py
  diamond_asterisk.py
Labels: hacktoberfest-accepted, accepted

#167 Create printAGivenDoublyLinkedListInReverseOrder.py
  printAGivenDoublyLinkedListInReverseOrder.py
Labels: hacktoberfest-accepted, accepted

#164 Added tower of hanoi in python
  Python Basic Programs/tower_of_hanoi.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#162 Added Valid Sudoku
  Python Basic Programs/ValidSudoku.py
Labels: hacktoberfest-accepted, accepted

#159 diameter_of_binary_tree added
  data_structures/binary_tree/diameter_of_binary_tree.py.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#177 Updated by Patterns.py and Keylogger.py
  Python Basic Programs/keylogger.py
  Python Basic Programs/patterns.py
Labels: hacktoberfest-accepted, accepted

#180 Rock Paper Scissors.py
  Rock Paper Scissors.py
Labels: hacktoberfest-accepted, accepted

#179 Added code for Guessing game challenge python script
  Python Basic Programs/Guessing Game Challenge.py
Labels: hacktoberfest-accepted

#176 Menu Driven Binary Operations
  menu-driven-binary-operations.py
Labels: hacktoberfest-accepted, accepted

#185 split data from file
  alarm_Clock.py
  split_data_sort_from_the_file/split_and_store_in_list.py
  split_data_sort_from_the_file/test.txt
Labels: hacktoberfest-accepted, accepted

#184 Added my deployed ML model
  Web and  Automation and Networking/house_pred_deployment.py
Labels: hacktoberfest-accepted, accepted

#173 Create fibonacci.py
  Python Basic Programs/fibonacci.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#183 Added url find program in python
  Python Basic Programs/url_find.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#181 Python Program for Depth First Search
  data_structures/dfs_Python/dfs.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#187 Create Shell_sort.py
  Python Basic Programs/Shell_sort.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#190 mean_median_mode in python
  Python Basic Programs/mean_median_mode.py
Labels: hacktoberfest-accepted, accepted

#205 Add: Information Fusion Algo
  Python Basic Programs/Information_Fusion
Labels: hacktoberfest-accepted, accepted

#196 Standard deviation and variance in python
  Python Basic Programs/standard_deviation_variance.py
Labels: hacktoberfest-accepted, accepted

#194 Create GUI Calendar
  PYTHON GUI/GUI Calendar/README.md
  PYTHON GUI/GUI Calendar/gui-calendar.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#209 Python basic program to count prime numbers in a defined interval
  Python Basic Programs/count_prime_in_defined_interval.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#207 sort-added
  data_structures/bubblesort.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#206 Add heap sorting algorithm in python
  Python Basic Programs/heapSort.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#204 Hangman
  Python Basic Programs/Hangman.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#203 Boruvka’s Algorithm in Python
  data_structures/Boruvkas_algorithm.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#202 Group Anagrams
  Python Basic Programs/Group Anagrams.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#199 added python gps
  gps/coordinates.py
  gps/display.html
  gps/findonmap.py
  gps/gps.py
  gps/gps_data.txt
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#201 Create snake game
  snake game
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#195 added 2048 GUI game
  PYTHON GUI/2048.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#191 Made a program to check internet speed test
  Python Basic Programs/internetspeedtest.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#189 Create counting_sort.py
  Python Basic Programs/counting_sort.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#188 Create insertionsort.py
  Python Basic Programs/insertionsort.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#172 Adding U-Net model
  AI ML/U-net.ipynb
Labels: hacktoberfest-accepted, accepted

#218 added COA Algorithms in python
  COA Algorithms/Binary Multiplication.py
  COA Algorithms/Booth Multiplication.py
  COA Algorithms/IEEE 754 Additon.py
  COA Algorithms/Non Restoring Division.py
  COA Algorithms/README.md
  COA Algorithms/Restoring Division.py
  COA Algorithms/Utils.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#217 Create Alarm_Clock.py
  Python Basic Programs/Alarm_Clock.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#214 Add web_blocker
  Web and  Automation and Networking/Web_blocker.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#232 Create 2Dgraphs.py
  PYTHON GUI/2Dgraphs.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#231 Add files via upload
  AI ML/SMS_Project.py
  AI ML/vieh_project.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#230 Heap Sort using Custom MaxHeap
  Python Basic Programs/heap-sort.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#229 Add files via upload
  Python Basic Programs/quicksort.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#228 Added Automatic Birthday Wisher Using Python
  PYTHON GUI/Automatic Birthday Wisher Using Python/data.xlsx
  PYTHON GUI/Automatic Birthday Wisher Using Python/main.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#227 Turtle Animations Added
  Python Basic Programs/Turtle_animations/hexagon.py
  Python Basic Programs/Turtle_animations/indianFlag.py
  Python Basic Programs/Turtle_animations/star.py
  Python Basic Programs/Turtle_animations/trihexagonal.py
  Python Basic Programs/Turtle_animations/viruspattern.py
  Python Basic Programs/keylogger.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#226 Added text to handwriting converter script
  Text to Handwritten/pywhatkit.png
  Text to Handwritten/requirements.txt
  Text to Handwritten/text-to-handwritten.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#221 Added Sudoku Solver
  Advanced python programs/sudoku_solver.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#220 Added one Classic Linear regression model
  AI ML/Linear Regression Model/Linearregression.ipynb
  AI ML/Linear Regression Model/Readme.md
  AI ML/Linear Regression Model/Screenshot 2022-10-07 153212.png
  AI ML/Linear Regression Model/Screenshot 2022-10-07 153430.png
  AI ML/Linear Regression Model/Week2_LR.ipynb
  AI ML/Linear Regression Model/Week2_Regression.ipynb
  AI ML/Linear Regression Model/homeprices.csv
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#216 Create Age_Calculator.py
  Python Basic Programs/Age_Calculator.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#215 Added ResNet
  AI ML/Resnet.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#213 Added Fibonacci sequence generator
  Python Basic Programs/Fibonacci.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#233 Add OddEven Sort Algorithm
  Arrays and Matrix/OddEvenSort.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#234 DiceRollingSimulator
  Python Basic Programs/DiceRollingSimulator.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#235 Hacktoberfest2022 steganography added
  Python Basic Programs/Steganography.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#239 railway assistance model
  railway_assistance.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#251 add visual a track with folium
  gps/visual_track/requirements.txt
  gps/visual_track/route.html
  gps/visual_track/track1.txt
  gps/visual_track/track_visu.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#241 Added Alien spaceship game in /PYTHON GUI
  PYTHON GUI/Alien Spaceship Game/.gitignore
  PYTHON GUI/Alien Spaceship Game/README.md
  PYTHON GUI/Alien Spaceship Game/alien.py
  PYTHON GUI/Alien Spaceship Game/alien_invasion.py
  PYTHON GUI/Alien Spaceship Game/alien_invasion_demo.gif
  PYTHON GUI/Alien Spaceship Game/bullet.py
  PYTHON GUI/Alien Spaceship Game/button.py
  PYTHON GUI/Alien Spaceship Game/game_functions.py
  PYTHON GUI/Alien Spaceship Game/game_stats.py
  PYTHON GUI/Alien Spaceship Game/images/alien.bmp
  PYTHON GUI/Alien Spaceship Game/images/ship.bmp
  PYTHON GUI/Alien Spaceship Game/scoreboard.py
  PYTHON GUI/Alien Spaceship Game/settings.py
  PYTHON GUI/Alien Spaceship Game/ship.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#245 Added Simple Linear regression Code
  AI ML/SLR/ReadMe.md
  AI ML/SLR/Simple Linear Regression.ipynb
  AI ML/SLR/ml_data_salary.csv
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#255 Fully working snake game added made using pygame library of python3
  snake.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#254 Added Student Management System to Python Basic Programs
  Python Basic Programs/Student_Management_System.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#253 Added Pairing heaps
  data_structures/PairingHeaps.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#252 added random forest algorithm
  AI ML/Random_Forest_Regressor.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#250 Create dicestimulator.py
  Python Basic Programs/dicestimulator.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#247 created a program to generate a heart pattern
  Python Basic Programs/heart.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#246 Add algorithms SelectionSort
  Arrays and Matrix/SelectionSort.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#259 Drinking Water Notification
  drinking/drink.py
  drinking/icon.ico
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#265 Create temperature_converter.py
  Python Basic Programs/acid_solution.py
  Python Basic Programs/pythagoras.py
  Python Basic Programs/temperature_converter.py
Labels: hacktoberfest2021, hacktoberfest-accepted, hacktoberfest, accepted

#261 Caeser_Cypher
  cypher.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#269 Facial Reaction Recognizer using python Added
  Face Reaction/app.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#268 Added pomodoro timer GUI in python.
  PYTHON GUI/pomodoro.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#275 Create python zip file brute forcer
  python zip file brute forcer
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#274 Virtual painter added
  Virtual-Painter/tools.png
  Virtual-Painter/virtual_paint_app.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#273 Create Discord_TextScraper.py
  Discord_TextScraper.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#272 ML-model-added
  US-forieghn-AID/US_foriegn_AID.ipynb
  US-forieghn-AID/us_foreign_aid_country.csv
Labels: hacktoberfest-accepted, accepted

#271 palindrome.py added
  Python Basic Programs/palindrome.py
Labels: hacktoberfest-accepted, accepted

#276 Added Candidate Elimination Problem
  AI ML/Candidate_Elimination_Problem/Candidate Elimination Problem.ipynb
  AI ML/Candidate_Elimination_Problem/dataset-1.csv
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#285 Added 8 ball program
  Python Basic Programs/8ball.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#282 Create rock_paper_scissor.py
  rock_paper_scissor.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#280 Create whstappbot.py
  Python Basic Programs/whstappbot.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#281 Tic-Ta-toe -game
  Arrays and Matrix/dynamic_sort.py
  PYTHON GUI/Tic-Tac-Toe-Game-In-Python-srishti/Gui.PNG
  PYTHON GUI/Tic-Tac-Toe-Game-In-Python-srishti/README.md
  PYTHON GUI/Tic-Tac-Toe-Game-In-Python-srishti/Tic_Tac_Toe_Game.py
  PYTHON GUI/Tic-Tac-Toe-Game-In-Python-srishti/Winning_message.PNG
  PYTHON GUI/Tic-Tac-Toe-Game-In-Python-srishti/draw_messge.PNG
  dynamic_sort.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#291 Added Python Turtle Projects
  Python Turtle Projects/Figure Designs/Among_Us.py
  Python Turtle Projects/Figure Designs/Avengers_logo.py
  Python Turtle Projects/Figure Designs/Batman.py
  Python Turtle Projects/Figure Designs/Captain_America_Shield.py
  Python Turtle Projects/Figure Designs/Doraemon.py
  Python Turtle Projects/Figure Designs/Ironman_Helmet.py
  Python Turtle Projects/Figure Designs/Panda.py
  Python Turtle Projects/Figure Designs/Pikachu.py
  Python Turtle Projects/Figure Designs/Robert_Downey_Jr.py
  Python Turtle Projects/Figure Designs/Shinchan.py
  Python Turtle Projects/Figure Designs/Tom_Holland.py
  Python Turtle Projects/Figure Designs/Yash.py
  Python Turtle Projects/Games Design/Pong_Game.py
  Python Turtle Projects/Games Design/Snake_Game.py
  Python Turtle Projects/Games Design/Two_Player_Game.py
  Python Turtle Projects/Pattern Designs/Animation_Circle.py
  Python Turtle Projects/Pattern Designs/Attractive_Circle.py
  Python Turtle Projects/Pattern Designs/Circle_Mania.py
  Python Turtle Projects/Pattern Designs/Circle_Ring.py
  Python Turtle Projects/Pattern Designs/Fractal_Art.py
  Python Turtle Projects/Pattern Designs/Graphics_Pattern.py
  Python Turtle Projects/Pattern Designs/Random_Flower_Design.py
  Python Turtle Projects/Pattern Designs/Spiral_Draw.py
  Python Turtle Projects/Pattern Designs/Spiral_Web.py
  Python Turtle Projects/Pattern Designs/Square_Spirograph.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#294 Added screen Pet face game
  Python Basic Programs/screen_Pet_Game.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted
